### ISSUE TITLE
No matching global declaration available for the validation root.

### ISSUE THREAD

**Issue by lennerd** [sulu-io/sulu#1676]
When installing sulu as described in the current guides and opening the admin area, I get this error:

````
[ERROR 1845] Element '{http://friendsofsymfony.github.com/schema/rest}routes': No
matching global declaration available for the validation root. (in {project}/web/
- line 4, column 0) in {project}/vendor/sulu/sulu/src/Sulu/Bundle/SecurityBundle
/Resources/config/routing_api.xml (which is being imported from "{project}/app
/config/admin/routing.yml").
````
*I replaced the project base urls with `{project}`*

Looks like a XML validation error, but I'm not quite sure if this is a bug in the software or me.

Any ideas?

**Comment by lennerd** [comment]
I did a recent `composer update` which updated sulu to c50de07ca6f5e6d45926e4f0167c474537d57c2d. Still the same error.

**Comment by wachterjohannes** [comment]
do you have changed something in this routing file? `"{project}/app
/config/admin/routing.yml"` if yes could you please upload it here?

**Comment by lennerd** [comment]
Thank you for the quick response.

No, I haven't. But here is the corressponding `routing.yml`:

```yaml
sulu_tag:
    resource: "@SuluTagBundle/Resources/config/routing.yml"
    prefix:   /admin/tag

sulu_tag_api:
    resource: "@SuluTagBundle/Resources/config/routing_api.yml"
    prefix:   /admin/api

sulu_admin:
    resource: "@SuluAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sulu_contact:
    resource: "@SuluContactBundle/Resources/config/routing.yml"
    prefix: /admin/contact

sulu_contact_api:
    type: rest
    resource: "@SuluContactBundle/Resources/config/routing_api.yml"
    prefix: /admin/api

sulu_security:
    resource: "@SuluSecurityBundle/Resources/config/routing.xml"
    prefix: /admin/security

sulu_security_api:
    type: rest
    resource: "@SuluSecurityBundle/Resources/config/routing_api.xml"
    prefix: /admin/api

sulu_content:
    resource: "@SuluContentBundle/Resources/config/routing.yml"
    prefix: /admin/content

sulu_content_api:
    type: rest
    resource: "@SuluContentBundle/Resources/config/routing_api.yml"
    prefix: /admin/api

sulu_media:
    resource: "@SuluMediaBundle/Resources/config/routing.yml"
    prefix: /admin/media

sulu_media_website:
    resource: "@SuluMediaBundle/Resources/config/routing_website.yml"

sulu_media_api:
    resource: "@SuluMediaBundle/Resources/config/routing_api.yml"
    prefix: /admin/api

sulu_category:
    resource: "@SuluCategoryBundle/Resources/config/routing.yml"
    prefix: /admin/category

sulu_category_api:
    resource: "@SuluCategoryBundle/Resources/config/routing_api.yml"
    prefix: /admin/api

sulu_snippet_api:
    resource: "@SuluSnippetBundle/Resources/config/routing_api.yml"
    type: rest
    prefix: /admin/api

sulu_location:
    resource: "@SuluLocationBundle/Resources/config/routing.yml"
    prefix: /admin/location

sulu_website:
    resource: "@SuluWebsiteBundle/Resources/config/routing.yml"
    prefix: /admin/website

sulu_websocket:
    type: rest
    resource: "@SuluWebsocketBundle/Resources/config/routing.yml"
    prefix: /admin/websocket

sulu_core:
    type: rest
    resource: "@SuluCoreBundle/Resources/config/routing_api.xml"
    prefix: /admin/api

# for preview
client_website:
    type: portal
    resource: "@ClientWebsiteBundle/Resources/config/routing.yml"

sulu_search:
    resource: "@SuluSearchBundle/Resources/config/routing.yml"
    prefix: /admin/search
```
