### ISSUE TITLE
Preview does not work with non-standard documents

### ISSUE THREAD

**Issue by danrot** [sulu-io/sulu#1886]
The scenario described in http://stackoverflow.com/questions/34120232/sulu-extend-pagedocument?noredirect=1#comment56338102_34120232 doesn't work as intended, as the error in this thread explains.

Main point is when creating an own document class and using it with this configuration in `app/config/config.yml`:

```yml
sulu_document_manager:
    mapping:
        page:
            class: Client\Bundle\WebsiteBundle\Document\PageDocument
            phpcr_type: sulu:page
```

The preview does not work, it just shows the following exception:
![image](https://cloud.githubusercontent.com/assets/405874/11851994/e2aac5dc-a435-11e5-8cf3-d05f6cf6643a.png)

After a fast research I could track that down to the deserialization part of the preview. When the class is serialized the document is of the right type (`Client\Bundle\WebsiteBundle\Document\PageDocument`), but after deserialization the type is again `Sulu\Bundle\ContentBundle\Document\PageDocument`.
