### ISSUE TITLE
Content staging

### ISSUE THREAD

**Issue by sagikazarmark** [sulu-io/sulu#2133]
Drupal (and eZ Publish) has this awesome feature, called content staging. It allows migrating content from a staging are to the live version of a site. By content, I mean "content", assets, etc.

Do you think it would be possible to implement such a feature in Sulu and if so, would you accept PRs against the core/consider adding it to the roadmap?

**Comment by wachterjohannes** [comment]
we have planned a drafting mode (for pages) for one of the next releases https://github.com/sulu-io/sulu/issues/2028 you should hook up in this discussion. for other "entities" we currently not plan any drafting. but we would love to see PR from you and we would help you as good as we can (:

**Comment by danrot** [comment]
As @wachterjohannes already mentioned we are already working on a drafting mode for pages, so it would probably be a good idea to wait until we have finished that, before starting working on something on your own.

However, the drafting mode we are implementing only is only staging the content managed in PHPCR. We already version the assets, so that could maybe be reused in this process. So instead of simply saving the ID of an assigned asset, we would also have to remember the version of the asset we were using. But this workflow probably needs some more thoughts...

**Comment by sagikazarmark** [comment]
Thanks for your response. It's quite good to hear this is on the roadmap. Since you are targeting businesses, I think it would be nice to actually have some kind of written roadmap.

**Comment by berndhep** [comment]
Márk, thank you for your interest in the Sulu roadmap. We're not planning to publish an extensive roadmap in the future. But we will start our monthly Sulu newsletter very soon where we will talk about future development and feature previews. Stay tuned!

**Comment by sagikazarmark** [comment]
Thanks, looking forward to it.

**Comment by danrot** [comment]
@debreczeniandras There are no plans in building such a solution into the core of Sulu. But @wachterjohannes has built [nanbando](https://github.com/nanbando/sulu), which might be helping in what you want to achieve.

**Comment by debreczeniandras** [comment]
Thanks @danrot, 

nanbando could be useful, but for the websites we are now developing, I opted for your core Drafting solution based on what you mentioned above 2 years ago.

(I will share the solution here in a litte bit more detail, since this is the first - if not the only - result in google for the keywords 'sulu content staging')

In **Staging** environment use the **same** workspace for default and live. 
(Allowing admins/editors to check more complex changes to content of the website before publishing.)

``` YAML
# config_staging
sulu_document_manager:
    versioning:
        enabled: true
    sessions:
        default:
            backend: "%phpcr_backend%"
            workspace: "%phpcr_workspace%"
            username: "%phpcr_user%"
            password: "%phpcr_pass%"
        live:
            backend: "%phpcr_backend%"
            workspace: "%phpcr_workspace%"
            username: "%phpcr_user%"
            password: "%phpcr_pass%"`
```
In **Production** keep the original - separated - session config.

``` YAML
# config_prod
sulu_document_manager:
    versioning:
        enabled: true
    sessions:
        default:
            backend: "%phpcr_backend%"
            workspace: "%phpcr_workspace%"
            username: "%phpcr_user%"
            password: "%phpcr_pass%"
        live:
            backend: "%phpcr_backend%"
            workspace: "%phpcr_workspace%_live"
            username: "%phpcr_user%"
            password: "%phpcr_pass%"`
```
As mentioned, this can even work with modifying existing content - thanks to Versioning.
